<?php
namespace App\Service;

class ManifestService
{
    private $manifestFile;

    public function __construct($manifestFile)
    {
        $this->manifestFile = $manifestFile;
    }

    public function get($key) {
        $manifest = json_decode(self::read($this->manifestFile));

        if ($key === '_all') {
            return $manifest;
        }

        return $manifest->{$key} ?? null;
    }

    /**
     * Returns the raw contents of the AssetMapper manifest.
     *
     * The file is generated by "php bin/console asset-map:compile", so fail
     * with a hint instead of a bare file_get_contents() warning.
     */
    public static function read(string $manifestFile): string
    {
        $content = is_file($manifestFile) ? file_get_contents($manifestFile) : false;

        if ($content === false) {
            throw new \RuntimeException(sprintf(
                'The asset manifest "%s" does not exist. Build the frontend ("npm run production") and run "php bin/console asset-map:compile" first.',
                $manifestFile
            ));
        }

        return $content;
    }
}
